import type { NextPage } from "next";
import Head from "next/head";
import { ResetPass } from "../components/ResetForm";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <h1 className="text-6xl text-center my-10">Reset-Password<span className="text-blue-500"></span></h1>
        <div className="container mx-auto my-10 max-w-7xl cpx-4 sm:px-6 lg:px-60">
          <ResetPass />
        </div>
      </main>
    </div>
  );
};
export default Home;